Fix warning typos, and fix MEV-Boost config update graffiti limit
dappnode/DAppNodePackage-teku-prater pull request #98
Opened 2022-11-28 01:22 UTC by alexpeterson91

Fix warning typos, and fix MEV-Boost config update graffiti limit

2022-11-28 21:00 UTC, 3alpha approved these changes

2023-02-13 02:50 UTC, alexpeterson91 commented
@pablomendezroyo please review This PR was marked P0 in November because of MEV-Boost issues, several of them.
 I updated the first post to detail the fixes that are causing a myriad of issues with teku, been trying to just get this done here on prater before dealing with mainnet, since its a problem i continue to see on discord now 2 months later, same issues.

2023-02-13 06:38 UTC, pablomendezroyo approved these changes

2023-02-17 06:31 UTC, 3alpha approved these changes

2023-02-21 15:31 UTC, dsimog01 requested changes

2023-02-21 15:31 UTC, dsimog01 commented on validator/entrypoint.sh
> +  if curl --retry 5 --retry-delay 5 --retry-connrefused "${MEVBOOST_URL}"; then
I think this is wrong @alexpeterson91 . If the curl GET is successful, then MEV-BOOST is reachable

2023-02-21 15:31 UTC, dsimog01 commented on validator/entrypoint.sh
> +  WEB3SIGNER_STATUS=$(curl -s http://web3signer.web3signer.dappnode:9000/healthcheck | jq '.status')
This is Teku Prater... So it is web3signer-prater

2023-02-21 15:31 UTC, dsimog01 commented on validator/entrypoint.sh
> +    echo yes | exec /opt/teku/bin/teku voluntary-exit --beacon-node-api-endpoint=http://beacon-chain.teku.dappnode:3500 \
Same as above

2023-02-28 15:49 UTC, closed without merging